---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  labels:
    app: postgresql
stringData:
  database-name: db
  database-password: CHANGEME
  database-user: dbuser
  database-root-password: CHANGEME
