apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
  name: oadp
  namespace: openshift-adp   
spec:
  targetNamespaces:
  - openshift-adp
