---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql
  labels:
    appname: postgresql
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "ocs-storagecluster-ceph-rbd"
  resources:
    requests:
      storage: 10Gi
