---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: oadp
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/ddomingu/odf-regional-dr.git
      revision: main
      files:
      - path: "oadp/cluster-definition/**/cluster.yaml"
  template:
    metadata:
      name: '{{cluster.name}}-oadp'
    spec:
      project: default
      source:
        repoURL: https://github.com/ddomingu/odf-regional-dr.git
        targetRevision: main
        path: oadp/components/overlays/{{cluster.name}}
      destination:
        server: '{{cluster.address}}'
        namespace: openshift-adp
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - PruneLast=true
