---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webserver-pv-claim
  labels:
    app: webserver
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: "ocs-storagecluster-cephfs"
  resources:
    requests:
      storage: 5Gi
