apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base/

patches:
- target:
    group: velero.io
    version: v1
    kind: BackupStorageLocation
  path: patch-bsl-prefix.yaml
